name: ODMEmilieItziarRedis
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pymongo
  - geopy
  - redis-py
  - geojson
  - pyyaml
  - pytest
  - tqdm
  - ipywidgets
  - notebook
  - ipykernel
  - jupyterlab